### ISSUE TITLE
calibrate and check_timeout blocks events in the loop

### ISSUE THREAD

**Issue by ceeaspb** [wg/wrk#116]
Calculating the X*R utilisation of 1 connection and 1 thread showed that there was significant time being "lost" in the event loop, where the tool is not applying load to the system or not capturing it.

Originally this was 20% for high frequency low latency tests (such as the spray benchmark), but with this change to move calibrate and check_timeouts to a separate thread and loop(this ticket) and fix start of latency measurement (#115) the "loss" is down to around 1.1% which seems more reasonable.

https://github.com/ceeaspb/wrk/commit/48586078976348cd668a1848b993bec544779d69

**Comment by wg** [comment]
Hi @ceeaspb, thanks again for all the great analysis. I have a new 'stats' branch of wrk-next available at https://glozer.net/src/wrk.git that I'd love your feedback on.

This branch gets rid of sampling entirely in favor of collecting all data. It also gets rid of the timeout loop which was always a bit of a questionable heuristic since it wasn't tied to the actual response. Overall I'm really happy with the new approach, it should be much more accurate and actually increases the maximum load generation rate.

That said I still have work to do, to improve handling of coordinated omission.

The calibration period occurs before the actual test starts, and results from that aren't included in the output, so I don't think moving it to a separate thread is necessary.

**Comment by ceeaspb** [comment]
ok thanks @wg , I'm getting 403 for the link currently

**Comment by wg** [comment]
@ceeaspb yeah it's just a git repo fetchable by HTTP but not browsable. I'll probably rebase a couple of times before I push to github.
