### ISSUE TITLE
Definition about timeout 

### ISSUE THREAD

**Issue by gabyoh** [wg/wrk#177]
Hi @wg,

Just I trying to confirm the result after execution. How can understand relation between: connect, read, write and finally timeout. For example:
69721 requests in 10.00m, 1.70GB read
Socket errors: connect 0, read 0, write 0, timeout 498
What does 0,0,0,and 498 mean? 
Thanks.
https://guides.github.com/features/mastering-markdown/

**Comment by wg** [comment]
Hi @gabyoh, those numbers mean 0 errors connecting, reading, and writing but 498 requests took longer than the timeout (which defaults to 2s and can be specified with the --timeout option).

**Comment by mnnit-geek** [comment]
Hi @wg ,
Quick question i'm confused between duration(-d) and --timeout option. I'm trying to benchmark and API and all the requests are getting timed out. Furthermore, setting more timeout is of no help it still yields the same result. Could you please help me understand how can I reduce the timeout numbers? Usually api takes 90secs to return the results.

wrk -t12 -c400 -d100s http://some-url/dcs/document/8dv-jc-dev/AdeemSample.xlsx/AdeemSample.xlsx -- debug true --timeout 100s
Running 2m test @ http://172.23.12.94:9999/dcs/document/8dv-jc-dev/AdeemSample.xlsx/AdeemSample.xlsx
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.32s   399.45ms   1.94s    61.76%
    Req/Sec     8.75      7.51   107.00     75.52%
  7067 requests in 1.67m, 5.77GB read
  Socket errors: connect 0, read 0, write 0, timeout 6965
Requests/sec:     70.60
Transfer/sec:     59.05MB

**Comment by Clorr** [comment]
Hi @mnnit-geek,
Just to answer about your wondering about duration and timeout (I'm sure you have found out but some other may also wonder):
- duration is the time for the whole test. You may want to run the test for a short or long period, it is up to you. A server should always behave the same, from the first second till the last, but sometimes it is not the case, and that is why specifying duration is handy
- timeout is the maximum time permitted for each single request. If you test a static file service, you expect it to be fast, and 2s should be enough. But if you test a big dynamic page, it may be slow, so you will have to increase the timeout in order to tell wrk to wait more for each request he does.

Hope this helps ;-)
