### ISSUE TITLE
What is exactly the meaning of thread and connection?

### ISSUE THREAD

**Issue by roysG** [wg/wrk#205]
Hi,
I want to make some test of 2000 users enter run specific url at the same time.
But i am afraid i have some confusing between connections and threads.

As i see it i need to run 2000 connection, if so, what the rule of thread here ?

Many thanks for your help, but the way, Amazing JOB.

**Comment by wg** [comment]
Hi @roysG, you've got it about right, 2000 connections would approximate 2000 "users" assuming a browser that only opens one connection. The total # of connections is distributed evenly amongst the threads which keep them open and submit requests on each connection. Generally the number of threads should equal the number of physical CPU cores you want wrk to use.

**Comment by roysG** [comment]
Thanks for your response :),
So if i have mac book pro middle 2011 with process of i5,  i need to run 4 threads that each one can handle lets say something like 2000 connection.

To summary it in shortly, can i run max test of 8000 connection("users"), at the same time?

**Comment by wg** [comment]
I'm not sure about your computer but Intel Core i5s generally only have two physical cores, though some may have hyper threading and support running 4 threads simultaneously. HT doesn't have the same performance as true physical cores, just allows some interleaving of execution of one thread stalls. I suggest you try the same test with 2 and 4 threads and see which shows better performance.

8000 connections is a lot, particularly for your CPU, and OSX performs poorly in general. However it may work if the bottleneck is server-side and the connections are mostly idle waiting for a response. For a fast HTTP server like nginx serving static content on Intel Xeon CPUs with many physical cores, running Linux, just 400 connections spread over 12 threads is enough to max out wrk's performance.

**Comment by roysG** [comment]
Ok, so if i did test result:

12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   512.04ms  481.63ms   2.00s    83.44%
    Req/Sec    32.33     18.48   168.00     71.27%
  64646 requests in 3.00m, 97.96MB read
  Socket errors: connect 0, read 8, write 0, timeout 8517
  Non-2xx or 3xx responses: 64646
Requests/sec:    358.97
Transfer/sec:    557.03KB


And i finish the test and in the middle of the test the server success to works correctly,
Is that mean that in case that  64646 users will enter my site, at the same time, the server will hold them?

**Comment by wg** [comment]
No, it means your server saw 64646 requests. Without pipelining each connection supports only one request at a time, so the maximum possible simultaneous requests is 400. Realistically though the actual number of concurrent requests was probably smaller. 12 threads is way too much for your system, try 2.

**Comment by roysG** [comment]
Now i am confusing again.. :(
What are the difference between connection and request?
As i tracking in my server, when the request start, it simulate a user that ask the request by the specific url.

If the "wrk" called 64646 times to my server,and my server response to request, as i see it, it emulate request of some user, No?

**Comment by wg** [comment]
To add to my previous reply, benchmarking is difficult to do correctly. Unless you already understand the performance characteristics of the systems you're testing you should start small, say 1 thread and 10 connections. Run a test like that for a few minutes, check that neither the client or server are at 100% capacity. If they aren't, gradually increased the number of connections until they are.

**Comment by wg** [comment]
@roysG HTTP 1.1 and up support sending many requests over the same connection. For HTTP 1.1 without pipelining only one request can be sent at a time, but as soon as a response is received the next request can be sent. If 400 connections are open then 400 requests can be sent and waiting for a reply.

**Comment by roysG** [comment]
Ok, and when i do it i need to check the number of request it sends and if i get 100% cpu and memory start to low then i need to make some scale, check for bottle neck or increase cpu and memory, till i get good result on high capacity, right?

But how do i know how much users it can handle, what parameter does tell me that?

**Comment by wg** [comment]
The best wrk can do is provide some numbers to help you estimate how many users your system might handle. Real users have very different behavior, their browsers open multiple connections to download resources like CSS, JS, images, etc concurrently and each user has different bandwidth and latency to your servers. Also the users of a real website don't hit the same URL over and over, they browse around opening different URLs at different rates.

There are tools that can record your browser's activity while accessing your site and replay them to simulate real users. That's generally called load testing not benchmarking and it's not really what wrk is designed to do, although you can approximate it with lua scripts. What wrk is designed to do is give you the maximum requests/sec and latency of a single URL at a given level of concurrency.

**Comment by roysG** [comment]
Great, but actually the users will open app and not site, so they will use the same request all times.

I tried to sent parameters as "get method", but i saw in my server that i did get just the first parameter from 7 other parameter.

The request was for example:
http://www.xxx.com/api/test?ui=kgdflgfdg&phone=23233232&fullname=ffdfTrt

What do i missing ?

**Comment by methane** [comment]
@roysG How about stop treating @wg as your personal support and go stackoverflow?

Using github issue tracker to ask personal question wastes OSS author's time.
It's a very limited resource.

Performance test is not an easy task.  It requires deep insights about your application and system.
The answer of question like "How I can benchmark my application?" can be a book.
For example, http://www.amazon.com/dp/0596520662/

**Comment by roysG** [comment]
Ok man, Thanks.

**Comment by terencechow** [comment]
I asked this question on [stack overflow](http://stackoverflow.com/questions/38907909/how-do-the-number-of-threads-affect-a-benchmark-with-wrk) but didn't get any answers. I thought I would add this to this post since it is closely related. 

I was reviewing the server benchmark test [here](https://gist.github.com/omnibs/e5e72b31e6bd25caf39a) which benchmarks various backend frameworks using this tool.

Looking at the code the client tests 100 connections over 20 threads, for 30 seconds hitting the backend url. (Both server and client are on separate rackspace machines).

What I'm trying to understand is what the 20 threads relate to? If for hypothetical purposes, the rackspace client machine can create 100 connections on 1 thread, what difference does it make that we use 20 threads? I understand the 100 connections can be thought of as users going to a website. But I don't understand the purpose of the threads. Is the purpose of using threads just to make sure we maximize our cpu such that when I test on rackspace I can use a lower compute machine to save myself money? Is that the only purpose of using extra threads? 

Any information will be greatly appreciated. Thanks!

**Comment by methane** [comment]
@terencechow 
That's a very basis of benchmarking network applications.
I hope all users learn such basis by themselves.  OSS creaters are not free teachers.

---

20 threads means wrk uses 20 OS threads, to use multiple cores.
I think number of CPU threads (cores) is enough for wrk threads, but someone prefer 2x CPU threads.

100 connections means 100 concurrency.
Since wrk is not tool for emulate real load from humans, 100 connections doesn't mean 100 users (browsers).  No one can push F5 key 10000 times a second.  But wrk can send 10000 requests on 1 connection.

Wrk is tool to measure throughput.  Concurrency is very important to measure throughput.
For example, when network RTT is 1ms, maximum roundtrip per seconds is only up to 1,000.
If the server can process 100,000 requests/sec (it's throughput), at least 100 connections is
required to measure throughput.
This example is most simple case.  In real world, latency is happen by various reasons.
You can't know good concurrency only from RTT between client and server.
You should increase concurrency until throughput is saturated.

**Comment by terencechow** [comment]
Thank you very much @methane I was indeed trying to learn on my own but you definitely clarified things for me. Thanks!

**Comment by xjtushilei** [comment]
Hello! My data is generated by lua script, but it can't generate a lot of load, even no more than 10,000 qps. And our needs need to generate more than 100,000, is it a lua script performance reason?

And wrk's cpu kernel time is particularly high! So is there a problem with wrk and lua script switching?

**Comment by alielmajdaoui** [comment]
> @terencechow That's a very basis of benchmarking network applications. I hope all users learn such basis by themselves. OSS creaters are not free teachers.
> 
> 20 threads means wrk uses 20 OS threads, to use multiple cores. I think number of CPU threads (cores) is enough for wrk threads, but someone prefer 2x CPU threads.
> 
> 100 connections means 100 concurrency. Since wrk is not tool for emulate real load from humans, 100 connections doesn't mean 100 users (browsers). No one can push F5 key 10000 times a second. But wrk can send 10000 requests on 1 connection.
> 
> Wrk is tool to measure throughput. Concurrency is very important to measure throughput. For example, when network RTT is 1ms, maximum roundtrip per seconds is only up to 1,000. If the server can process 100,000 requests/sec (it's throughput), at least 100 connections is required to measure throughput. This example is most simple case. In real world, latency is happen by various reasons. You can't know good concurrency only from RTT between client and server. You should increase concurrency until throughput is saturated.

Who agrees that this explanation should be in the README?

**Comment by code-jpeg** [comment]
rtyuio
