### ISSUE TITLE
Difference between `Req/Sec` and `Requests/sec`?

### ISSUE THREAD

**Issue by palaiyacw** [wg/wrk#259]
what is the difference between `Req/Sec` and `Requests/sec`? In the below example which is given in your documentation. both the values are different. Could you please provide the links for the same also where it is explained?

```
Running 30s test @ http://127.0.0.1:8080/index.html
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   635.91us    0.89ms  12.92ms   93.69%
    Req/Sec    56.20k     8.07k   62.00k    86.54%
  22464657 requests in 30.00s, 17.76GB read
Requests/sec: 748868.53
Transfer/sec:    606.33MB
```

**Comment by defanator** [comment]
Hi @palaiyacw,

Req/Sec represents numbers obtained per thread, while Requests/sec is a total from all threads.

**Comment by palaiyacw** [comment]
@defanator 

I ran `wrk` for 1 thread and following are the result. Why there is a difference between `Req/Sec` and  `Requests/sec`.

```
 wrk -t1 -c100 -d20s http://172.16.5.40:8082/test
Running 20s test @ http://172.16.5.40:8082/test
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    59.61ms  172.66ms   1.31s    94.03%
    Req/Sec     7.10k     3.14k   14.39k    72.47%
  127061 requests in 20.01s, 14.06MB read
Requests/sec:   6348.95
Transfer/sec:    719.22KB
```

**Comment by knasim** [comment]
@palaiyacw - interesting observation - what was the cause

**Comment by lanphan** [comment]
@knasim can you give more information why Req/sec and Requests/sec are different for 1 thread case?
In addition, when we run tests for 1 thread case, which number (Req/sec or Requests/sec) is more accurate?
Thanks.

**Comment by knasim** [comment]
@lanphan - the reason is it depends on how many connections the program is able to open on the OS that it is running - depends on IO.  A further examination of the source code would be required.   

you have to look at all the figures that the program returns after the stress test. it is not a question of looking at one over the others.  you have to do a composite analysis.  there is also another flag you can provide to get more details on latency as well.

**Comment by wg** [comment]
Thanks @defanator & @knasim!

In addition to `Latency` and `Req/Sec` being per-thread stats, they're also statistics periodically captured during a benchmarking run. So `avg` is the average req/sec over the testing interval whereas `Requests/sec` is simply total requests / total time.

**Comment by yangboyd** [comment]
> Thanks @defanator & @knasim!
> 
> In addition to `Latency` and `Req/Sec` being per-thread stats, they're also statistics periodically captured during a benchmarking run. So `avg` is the average req/sec over the testing interval whereas `Requests/sec` is simply total requests / total time.

It'd better to add this to the first page readme.
There is another question: Does the Requests mean successful requests or initialized requests(include failed requests)?

**Comment by baiwfg2** [comment]
@defanator `Req/Sec represents numbers obtained per thread`, While I look at the code, `statistics.requests` is a global metric that is atomically modified by multiple threads, and `Req/Sec` derives from it (Obviously it's not per-thread metric, otherwise there'll be many lines of `Req/Sec`). Am I wrong ?

**Comment by baiwfg2** [comment]
I suppose these two are fairly unrelated. If we're gonna tell people what the benchmarking's qps is, I'd say the number of `Requests/Sec` instead of ` Avg of Req/Sec`. Is that right ?

**Comment by jrochkind** [comment]
Hm, if I'm runing with `-c 1 -t 1` should I expect `Thread Stats => Req/sec` to be the same as the `Requests/sec`? Or at least close?

Because they are not for me. My `Req/sec` is always twice or more the `Requests/sec` when running with `-c 1 -t 1`. 

I'm not sure if indicates  I am not understanding "connections" and "threads" settings correctly, or that I'm not understanding what req/sec and/or Requests/sec mean. 

I am just getting started using wrk and I love it -- but I need to understand what the values in the report mean to know what to take from the report!  More docs would be super useful. 

Here are two examples against two different sites, both showing a Req/Sec twice or more the Requests/Sec. 

```
Running 3m test @ [site]
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   309.22ms  386.30ms   2.57s    86.42%
    Req/Sec    11.67      8.85    38.00     70.75%
  Latency Distribution
     50%   97.95ms
     75%  449.39ms
     90%  847.98ms
     99%    1.68s
  962 requests in 3.00m, 176.59MB read
Requests/sec:      5.34
Transfer/sec:      0.98MB
```

and

```
Running 3m test @ [site]
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   522.18ms  679.45ms   3.94s    86.42%
    Req/Sec     7.46      5.52    30.00     65.29%
  Latency Distribution
     50%  160.24ms
     75%  772.34ms
     90%    1.47s
     99%    3.13s
  458 requests in 3.00m, 78.96MB read
  Socket errors: connect 0, read 0, write 0, timeout 1
  Non-2xx or 3xx responses: 16
Requests/sec:      2.54
Transfer/sec:    448.93KB
```

I don't understand what to take from the fact that these are so different.
