### ISSUE TITLE
Structured benchmark output

### ISSUE THREAD

**Issue by sscarduzio** [wg/wrk#313]
Would be really nice to have an option to output the results of the benchmark in a machine-friendly format like CSV/JSON/XML or whatever.

**Comment by wg** [comment]
This is possible using the reporting API as demonstrated in https://github.com/wg/wrk/blob/master/scripts/report.lua, and documented in https://github.com/wg/wrk/blob/master/SCRIPTING. However I don't want to include a bunch of different report output scripts with wrk itself due to the maintenance burden.

**Comment by centminmod** [comment]
if not included in wrk itself, what about just a few more fleshed out wiki examples at https://github.com/wg/wrk/wiki ?
