### ISSUE TITLE
Cannot build under WSL

### ISSUE THREAD

**Issue by mihab** [wg/wrk#362]
I get the following error when trying to build under Windows 10 WSL

`miha@DESKTOP-CEC4TIT:/mnt/c/Users/miha/Dev/wrk$ make
LUAJIT src/wrk.lua
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:63: recipe for target 'obj/bytecode.o' failed
make: *** [obj/bytecode.o] Error 2
miha@DESKTOP-CEC4TIT:/mnt/c/Users/miha/Dev/wrk$`

Any ideas?

**Comment by ltieman** [comment]
Use sudo make and it should build correctly.  Was having the same issue until I used sudo make.

**Comment by mihab** [comment]
Yup that was it, thanks a lot for the help!

**Comment by RobertoPrevato** [comment]
Yes, this is the same problem I found, and resolved with the change in my pull request.

**Comment by offero** [comment]
but why?

**Comment by RobertoPrevato** [comment]
> but why?

I think using `sudo` only works "by accident" because the sudo user has a $PATH env variable that doesn't contain spaces. My solution is better because it resolves the root problem: handling of $PATH variables with spaces. Take a look at my commit, here: [https://github.com/RobertoPrevato/wrk/commit/9d33c16d70d7b308650e89a7bd6b6de49430415e](https://github.com/RobertoPrevato/wrk/commit/9d33c16d70d7b308650e89a7bd6b6de49430415e).

Unfortunately people handling this repository seem to ignore completely PRs.
