### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by proyb6** [wg/wrk#448]
Need to fix link against ARM64 or any other alternative you can suggest?

```
*** Installing runtime programs
install apps/openssl -> /Users/x/Downloads/wrk-master/obj/bin/openssl
install ./tools/c_rehash -> /Users/x/Downloads/wrk-master/obj/bin/c_rehash
CC src/wrk.c
CC src/net.c
CC src/ssl.c
CC src/aprintf.c
CC src/stats.c
CC src/script.c
CC src/units.c
CC src/ae.c
CC src/zmalloc.c
CC src/http_parser.c
LUAJIT src/wrk.lua
fatal: not a git repository (or any of the parent directories): .git
LINK wrk
ld: warning: ignoring file obj/lib/libssl.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64ld: warning: ignoring file obj/lib/libcrypto.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

ld: missing LC_SEGMENT file 'obj/bytecode.o' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wrk] Error 1
```

**Comment by bobrik** [comment]
There are a few missing pieces here:

#### Bundled openssl is getting built for x86_64 and it's too old to support aarch64. 

There is no released stable version of openssl with `darwin64-arm64`, target:

* https://github.com/openssl/openssl/commit/23f04372f45f8c9e3865c3bcfee3f77a9cc10673

#### Luajit produces a fat object file `obj/bytecode.o`.

I have no idea why this upsets the linker. I've tried producing a single-arch non-fat object file, but that requires changing luajit code and it doesn't work as the only mitigation. It's possible to produce a C file and let wrk Makefile do the compilation:

* https://github.com/bobrik/wrk/commit/34794963a94139f7b11f94cc1b670fbe0db4e122

#### Linker flags for macOS break the resulting binary

Even if you link against the right openssl and make `obj/bytecode.o` satisfy the linker, the resulting binary will crash immediately:

```
$ wrk --version
Killed: 9
```

This error isn't particularly useful, but running under lldb reveals the issue:

```
$ lldb wrk
(lldb) target create "wrk"
Current executable set to 'wrk' (arm64).
(lldb) process launch -- --version
error: Malformed Mach-o file
```

It turns out that the following line in the Makefile is to blame:

```
LDFLAGS += -pagezero_size 10000 -image_base 100000000
```

This comes directly from luajit docs:

* https://luajit.org/install.html

<img width="636" alt="image" src="https://user-images.githubusercontent.com/89186/103141010-18864b80-46a3-11eb-84bb-0ed365ff8aba.png">

One can disable this for aarch64:

* https://github.com/bobrik/wrk/commit/7784f896b20de38a51e2a214523c7b135b443d14

If you do all this, you can get your working wrk natively on arm64:

```
$ file $(which wrk)
/Users/ivan/.nix-profile/bin/wrk: Mach-O 64-bit executable arm64

$ wrk -d 1s -t 1 -c 1 https://ivan.computer/
Running 1s test @ https://ivan.computer/
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    17.30ms    3.26ms  29.53ms   82.46%
    Req/Sec    56.30     11.70    70.00     70.00%
  57 requests in 1.01s, 97.04KB read
Requests/sec:     56.19
Transfer/sec:     95.66KB
```

**Comment by PeterKieu** [comment]
Can you zip the executive built file wrk? Or post it on docker hub

**Comment by wg** [comment]
Thank you for the detailed investigation & solutions @bobrik! With the latest commits on master wrk should build & run on Apple's new M1 machines.

**Comment by PeterKieu** [comment]
Perfect! Now I can make wrk and run on Macbook Air M1.
Thanks much indeed!
