### ISSUE TITLE
Pass a list of urls to wrk?

### ISSUE THREAD

**Issue by epugh** [wg/wrk#80]
I've been playing with siege, but unfortunately siege doesn't work with passing JSON content to API's.   One of the features I liked was it was easy to provide it a million urls to run over.  Anything like that in wrk?   Should I be hacking around with lua scripts?

**Comment by malthe** [comment]
Example?

**Comment by epugh** [comment]
@malthe I ended up not pursuing wrk

**Comment by wg** [comment]
@czerasz recently put together a very nice tutorial on doing just this: http://czerasz.com/2015/07/19/wrk-http-benchmarking-tool-example/

**Comment by ephes** [comment]
Hiho,

thanks for this great project :).

I've got wrk working with a custom url list with the lua script approach from above. Is it somehow possible to stop wrk after all urls were processed? Maybe returning an empty request or something like that? If there's no easy way I'll just change my other benchmark scripts to just run for a fixed time frame instead of a fixed url list. Should work too.

best regards,
jochen

**Comment by wg** [comment]
Hi @ephes, you can call `thread:stop()` from each thread.

**Comment by ephes** [comment]
Oh cool, thanks a lot :)
